version: "3.9"
services:
  resume_arin:
    build: .
    container_name: resume_arin
    ports:
    - "3001:3001"
    restart: unless-stopped
    labels:
    - "traefik.http.routers.arin_resume.rule=Host(`arin.sinabian.se`)"
    - "traefik.http.routers.arin_resume.priority=99"
    - "traefik.http.routers.arin_resume.tls=true"
    - "traefik.http.routers.arin_resume.tls.certresolver=myresolver"