version: "3.9"
services:
  resume_arin:
    image: resume:v1.4.3
    build: .
    container_name: resume_arin
    environment:
      - PORT=3001
    ports:
    - "3001:3001"
    restart: unless-stopped
    labels:
    - "traefik.http.routers.arin_resume.rule=Host(`arin.sinabian.se`)"
    - "traefik.http.routers.arin_resume.priority=99"
    - "traefik.http.routers.arin_resume.tls=true"
    - "traefik.http.routers.arin_resume.tls.certresolver=myresolver"
    - "traefik.http.routers.arin_resume.middlewares=arin_resume"
    - "traefik.http.middlewares.arin_resume.redirectscheme.scheme=https"
    - "traefik.http.routers.whoami.entrypoints=web"